# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CHOOSE.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CHOOSEMainWindow(object):
    def setupUi(self, CHOOSEMainWindow):
        CHOOSEMainWindow.setObjectName("CHOOSEMainWindow")
        CHOOSEMainWindow.resize(602, 600)
        CHOOSEMainWindow.setStyleSheet("background-color: rgb(12, 12, 12);")
        self.centralwidget = QtWidgets.QWidget(CHOOSEMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Chambre_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Chambre_btn.setGeometry(QtCore.QRect(82, 110, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Chambre_btn.setFont(font)
        self.Chambre_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Chambre_btn.setStyleSheet("#Chambre_btn{\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(5, 236, 239);\n"
"}\n"
"#Chambre_btn:pressed{\n"
"background-color: rgb(44, 29, 255);\n"
"}")
        self.Chambre_btn.setObjectName("Chambre_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setItalic(True)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.Visiteur_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Visiteur_btn.setGeometry(QtCore.QRect(80, 250, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Visiteur_btn.setFont(font)
        self.Visiteur_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Visiteur_btn.setStyleSheet("#Visiteur_btn{\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(87, 255, 15);\n"
"}\n"
"#Visiteur_btn:pressed{\n"
"background-color: rgb(17, 145, 10);\n"
"}")
        self.Visiteur_btn.setObjectName("Visiteur_btn")
        self.Reservation_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Reservation_btn.setGeometry(QtCore.QRect(80, 390, 421, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Reservation_btn.setFont(font)
        self.Reservation_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Reservation_btn.setStyleSheet("#Reservation_btn{\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(255, 239, 11);\n"
"}\n"
"#Reservation_btn:pressed{\n"
"background-color: orange;\n"
"}")
        self.Reservation_btn.setObjectName("Reservation_btn")
        CHOOSEMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CHOOSEMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 29))
        self.menubar.setObjectName("menubar")
        CHOOSEMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CHOOSEMainWindow)
        self.statusbar.setObjectName("statusbar")
        CHOOSEMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CHOOSEMainWindow)
        QtCore.QMetaObject.connectSlotsByName(CHOOSEMainWindow)

    def retranslateUi(self, CHOOSEMainWindow):
        _translate = QtCore.QCoreApplication.translate
        CHOOSEMainWindow.setWindowTitle(_translate("CHOOSEMainWindow", "MainWindow"))
        self.Chambre_btn.setText(_translate("CHOOSEMainWindow", "Chambre Screen "))
        self.label.setText(_translate("CHOOSEMainWindow", "Choose One :"))
        self.Visiteur_btn.setText(_translate("CHOOSEMainWindow", "Visiteur Screen"))
        self.Reservation_btn.setText(_translate("CHOOSEMainWindow", "Reservation Screen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CHOOSEMainWindow = QtWidgets.QMainWindow()
    ui = Ui_CHOOSEMainWindow()
    ui.setupUi(CHOOSEMainWindow)
    CHOOSEMainWindow.show()
    sys.exit(app.exec_())
