# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RESERVATION.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RESERVATIONMainWindow(object):
    def setupUi(self, RESERVATIONMainWindow):
        RESERVATIONMainWindow.setObjectName("RESERVATIONMainWindow")
        RESERVATIONMainWindow.resize(800, 600)
        RESERVATIONMainWindow.setStyleSheet("background-color: rgb(58, 197, 58);")
        self.centralwidget = QtWidgets.QWidget(RESERVATIONMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 0, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 85, 255);")
        self.label_2.setObjectName("label_2")
        self.NumDays_input = QtWidgets.QLineEdit(self.centralwidget)
        self.NumDays_input.setGeometry(QtCore.QRect(340, 350, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.NumDays_input.setFont(font)
        self.NumDays_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255)")
        self.NumDays_input.setText("")
        self.NumDays_input.setObjectName("NumDays_input")
        self.Add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_btn.setGeometry(QtCore.QRect(340, 460, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Add_btn.setFont(font)
        self.Add_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Add_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 0);\n"
"")
        self.Add_btn.setObjectName("Add_btn")
        self.Date_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Date_input.setGeometry(QtCore.QRect(340, 260, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Date_input.setFont(font)
        self.Date_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255)")
        self.Date_input.setText("")
        self.Date_input.setObjectName("Date_input")
        self.NumberBedroom_input = QtWidgets.QLineEdit(self.centralwidget)
        self.NumberBedroom_input.setGeometry(QtCore.QRect(342, 170, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.NumberBedroom_input.setFont(font)
        self.NumberBedroom_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255)")
        self.NumberBedroom_input.setText("")
        self.NumberBedroom_input.setObjectName("NumberBedroom_input")
        self.Delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Delete_btn.setGeometry(QtCore.QRect(600, 460, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.Delete_btn.setFont(font)
        self.Delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Delete_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 0, 0);\n"
"")
        self.Delete_btn.setObjectName("Delete_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 301, 491))
        font = QtGui.QFont()
        font.setPointSize(104)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"border:2px  solid rgb(46, 46, 255);\n"
"border-radius: 80px")
        self.label.setObjectName("label")
        self.NumVisitor_input = QtWidgets.QLineEdit(self.centralwidget)
        self.NumVisitor_input.setGeometry(QtCore.QRect(340, 90, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.NumVisitor_input.setFont(font)
        self.NumVisitor_input.setStyleSheet("border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: white;\n"
"padding-bottom:7px;\n"
"color: rgb(255, 255, 255)")
        self.NumVisitor_input.setText("")
        self.NumVisitor_input.setObjectName("NumVisitor_input")
        RESERVATIONMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RESERVATIONMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        RESERVATIONMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RESERVATIONMainWindow)
        self.statusbar.setObjectName("statusbar")
        RESERVATIONMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RESERVATIONMainWindow)
        QtCore.QMetaObject.connectSlotsByName(RESERVATIONMainWindow)

    def retranslateUi(self, RESERVATIONMainWindow):
        _translate = QtCore.QCoreApplication.translate
        RESERVATIONMainWindow.setWindowTitle(_translate("RESERVATIONMainWindow", "MainWindow"))
        self.label_2.setText(_translate("RESERVATIONMainWindow", "GERER RESERVATION"))
        self.NumDays_input.setPlaceholderText(_translate("RESERVATIONMainWindow", "Number of days                     "))
        self.Add_btn.setText(_translate("RESERVATIONMainWindow", "Add "))
        self.Date_input.setPlaceholderText(_translate("RESERVATIONMainWindow", "Date                                    "))
        self.NumberBedroom_input.setPlaceholderText(_translate("RESERVATIONMainWindow", "Number of bedroom               "))
        self.Delete_btn.setText(_translate("RESERVATIONMainWindow", "Delete "))
        self.label.setText(_translate("RESERVATIONMainWindow", ""))
        self.NumVisitor_input.setPlaceholderText(_translate("RESERVATIONMainWindow", "Number of visitor                   "))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     RESERVATIONMainWindow = QtWidgets.QMainWindow()
#     ui = Ui_RESERVATIONMainWindow()
#     ui.setupUi(RESERVATIONMainWindow)
#     RESERVATIONMainWindow.show()
#     sys.exit(app.exec_())
